analyzer_rules:
  - capture_variable
  - explicit_self
  - typesafe_array_init
  - unused_declaration
  - unused_import

disabled_rules:
  - inclusive_language

opt_in_rules:
  - accessibility_label_for_image
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - return_value_from_void_function
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# NOT opted in:
# - anonymous_argument_in_multiline_closure
# - balanced_xctest_lifecycle
# - discouraged_none_name
# - discouraged_optional_boolean
# - discouraged_optional_collection
# - explicit_acl
# - explicit_enum_raw_value -- WREAKS HAVOC WITH CodingKeys
# - explicit_top_level_acl -- FALSE POSITIVES ON PROTOCOL CONFORMANCE EXTENSIONS
# - explicit_type_interface
# - extension_access_modifier -- OPPOSITE OF WHAT SWIFT STDLIB DOES
# - file_header
# - file_name
# - file_types_order
# - function_default_parameter_at_end
# - indentation_width
# - legacy_objc_type
# - missing_docs
# - multiline_arguments_brackets
# - multiline_function_chains
# - multiline_literal_brackets
# - multiline_parameters_brackets
# - no_extension_access_modifier
# - no_grouping_extension
# - nslocalizedstring_require_bundle
# - prefer_nimble
# - prefixed_toplevel_constant
# - prohibited_interface_builder
# - required_deinit
# - strict_fileprivate
# - test_case_accessibility
# - type_contents_order
# - unowned_variable_capture
# - vertical_whitespace_opening_braces

included:
  - Sources
  - Tests

reporter: "xcode"

closure_body_length:
  warning: 40
  error: 60
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true
enum_case_associated_values_count:
  warning: 6
file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true
function_body_length:
  warning: 100
  error: 200
function_parameter_count:
  warning: 8
  error: 10
identifier_name:
  max_length: 50
  min_length: 1
large_tuple:
  warning: 3
  error: 4
line_length:
  warning: 150
  ignores_comments: true
  ignores_function_declarations: false
  ignores_urls: true
vertical_whitespace:
  max_empty_lines: 1
